module.exports = {
	"HOME_TITLE" : "Home",

	"HOME_MESSAGE_FIRST_OPEN" : "Wilkommen zu Arya! Durch Wischen kannst du deinen Lieblingshintergrund auswählen.",
	"HOME_MESSAGE_ZERO_JOURNALS" : "Mach dich an deinen ersten Eintrag für diese Woche",
	"HOME_MESSAGE_ONE_JOURNAL" : "eintrag diese Woche.",
	"HOME_MESSAGE_MULTIPLE_JOURNALS" : "einträge diese Woche.",

	"ME_TITLE" : "ICH",

	"JOURNALS_TITLE" : "Meine Einträge",
	"JOURNAL_TITLE" : "Mein Eintrag",
	"JOURNAL_UNANSWERED" : "Nicht beantwortet",

	"NOTES_TITLE" :"Meine Notizen",

	"QUESTION_FEELING_TITLE" : "Wie fühlst du dich?",
	"QUESTION_FEELING_SUBTITLE" : "Stell dein persönliches Stimmungsbarometer ein!",
	"QUESTION_FEELING_EXPLANATION" : "Spür in dich hinein - Wie geht es dir gerade? Wie ist deine individuelle Wetterlage?  Heiter oder eher wolkig?\nMach eine kurze allgemeine Inventur. Gar nicht lange überlegen. Folge deinem Impuls und bewege den Regler, um deine momentane Stimmung einzustellen.",
	"QUESTION_FEELING_VERY_BAD" : "SEHR SCHLECHT",
	"QUESTION_FEELING_AVERAGE" : "DURCHSCHNITTLICH",
	"QUESTION_FEELING_VERY_WELL" : "SEHR GUT",

	"QUESTION_CIRCUMSTANCES_TITLE" : "Beschreibe die Situation",
	"QUESTION_CIRCUMSTANCES_SUBTITLE" : "Wie ist die persönliche Lage der Nation? Gibt es Gründe für deine Stimmung?",
	"QUESTION_CIRCUMSTANCES_EXPLANATION" : "Denk jetzt mal kurz nach. Gibt es einen bestimmten Grund oder Auslöser für deine derzeitige Stimmung? Und wer oder was ist aus deiner Sicht dafür verantwortlich? Beschreibe die Situation samt Grund. Wenn dir dazu gerade nichts einfällt, dann beschreibe einfach nur diesen Moment. Orte,  Tätigkeiten, beteiligte Menschen, Geräusche, Gerüche, Sonstiges - was auch immer dir dazu in den Sinn kommt.",

	"QUESTION_BODY_TITLE" : "Wie fühlt sich Dein Körper an?",
	"QUESTION_BODY_SUBTITLE" : "Welche Empfindungen nimmst du wo in deinem Körper wahr?",
	"QUESTION_BODY_EXPLANATION" : "Nimm dir nochmal Zeit und gehe auf innere Spurensuche. Was spürst du wo im Körper? Welche Empfindungen kannst du wahrnehmen? Wo ist dir warm und wohlig? Wo kribbelts? Wo ziepts? Wo tuts richtig weh? Wo ist mehr Weite und wo ist alles enger als sonst? Hüpft das Herz oder krampft der Magen? Zuckt das Auge? Es geht so Vieles in dir vor. Beobachte alles sorgfältig, tippe auf die Abbildung der Körperteile, um dort deine Empfindungen zu notieren.",

	"QUESTION_BODY_HEAD" : "Kopf",
	"QUESTION_BODY_NECK" : "Nacken",
	"QUESTION_BODY_CHEST" : "Brust",
	"QUESTION_BODY_ABDOMEN" : "Bauch",
	"QUESTION_BODY_UPPER_BACK" : "Oberer Rücken",
	"QUESTION_BODY_LOWER_BACK" : "Unterer Rücken",
	"QUESTION_BODY_HIP" : "Hüfte",
	"QUESTION_BODY_LEFT_SHOULDER" : "Linke Schulter",
	"QUESTION_BODY_LEFT_ELBOW" : "Linker Ellenbogen",
	"QUESTION_BODY_LEFT_HAND" : "Linke Hand",
	"QUESTION_BODY_LEFT_ARM" : "Linker Arm",
	"QUESTION_BODY_LEFT_THIGH" : "Linker Oberschenkel",
	"QUESTION_BODY_LEFT_KNEE" : "Linkes Knie",
	"QUESTION_BODY_LEFT_ANKLE" : "Linker Knöchel/Fuß",
	"QUESTION_BODY_LEFT_LEG" : "Linkes Bein",

	"QUESTION_BODY_RIGHT_SHOULDER" : "Rechte Schulter",
	"QUESTION_BODY_RIGHT_ELBOW" : "Rechter Ellenbogen",
	"QUESTION_BODY_RIGHT_HAND" : "Rechte Hand",
	"QUESTION_BODY_RIGHT_ARM" : "Rechter Arm",
	"QUESTION_BODY_RIGHT_THIGH" : "Rechter Oberschenkel",
	"QUESTION_BODY_RIGHT_KNEE" : "Rechtes Knie",
	"QUESTION_BODY_RIGHT_ANKLE" : "Rechter Knöchel/Fuß",
	"QUESTION_BODY_RIGHT_LEG" : "Rechtes Bein",

	"QUESTION_BODY_HEADACHE" : "Kopfschmerzen",
	"QUESTION_BODY_FLUSHED_FACE" : "Errötet",
	"QUESTION_BODY_DIZZY_AND_LIGHTHEADED" : "Schwindel und Bennommenheit",
	"QUESTION_BODY_HEAVYHEADED" : "Schwerer Kopf",
	"QUESTION_BODY_NECK_PAIN" : "Nackenschmerzen",

	"QUESTION_BODY_HEAD_OPTIONS" : ["Kopfschmerzen","Erröted","Schwindel und Bennommenheit","Schwerer Kopf","Nackenschmerzen","Brennende Augen","Mundtrockenheit","Ohrenschmerzen"],
	"QUESTION_BODY_CHEST_OPTIONS" : ["Brustschmerzen","Atemprobleme","Druck auf der Brust","Herzrasen","Rückenschmerzen","Steifheit"],
	"QUESTION_BODY_ABDOMEN_OPTIONS" : ["Schmetterlinge im Bauch","Magenschmerzen","Übelkeit","Unterleibsschmerzen"],
	"QUESTION_BODY_LEFT_ARM_OPTIONS" : ["Gelenkschmerzen"],
	"QUESTION_BODY_RIGHT_ARM_OPTIONS" : ["Gelenkschmerzen"],
	"QUESTION_BODY_HIP_OPTIONS" : [],
	"QUESTION_BODY_LEFT_LEG_OPTIONS" : ["Gelenkschmerzen"],
	"QUESTION_BODY_RIGHT_LEG_OPTIONS" : ["Gelenkschmerzen"],
	"QUESTION_BODY_GENERIC_OPTIONS" : ["Hitze","Wärme","Kälte","Leichtigkeit","Schwere","Jucken","Prickeln","Anspannung","Taubheit","Muskelschmerzen","Kribbeln"],

	"QUESTION_BODY_CHEST_PAIN" : "Brustschmerzen",
	"QUESTION_BODY_BREATHING" : "Atemprobleme",
	"QUESTION_BODY_PRESSURE_CHEST" : "Druck auf der Brust",
	"QUESTION_BODY_HEARTBEAT" : "Herzrasen",
	"QUESTION_BODY_BACK_PAIN" : "Rückenschmerzen",
	"QUESTION_BODY_STIFNESS" : "Steifheit",

	"QUESTION_BODY_DIGESTIVE" : "Magenschmerzen",
	"QUESTION_BODY_NAUSEOUS" : "Übelkeit",
	"QUESTION_BODY_CROTCH" : "Unterleibsschmerzen",

	"QUESTION_BODY_MUSCLE_ACHE" : "Muskelschmerzen",
	"QUESTION_BODY_JOINT_PAIN" : "Gelenkschmerzen",
	"QUESTION_BODY_NUMBNESS" : "Taubheit",
	"QUESTION_BODY_TINGLING" : "Kribbeln",

	"QUESTION_THOUGHTS_TITLE" : "Was denkst du?",
	"QUESTION_THOUGHTS_SUBTITLE" : "Welche Gedanken kommen hoch? Ganz ehrlich...;-)",	
	"QUESTION_THOUGHTS_EXPLANATION" : "Vielleicht schließt du kurz die Augen, nimmst fur ein paar Sekunden Deinen Atem wahr. Dann bist du in der besten Position um deine Gedanken zu beobachten.  Wie Wolken am Himmel kommen sie und ziehen davon, mal stürmisch, mal gemach. Lass sie ziehen, aber schreib sie auf",

	"QUESTION_REACTION_TITLE" : "Wie hast du reagiert?",
	"QUESTION_REACTION_SUBTITLE" : "Ist dir was aufgefallen?",
	"QUESTION_REACTION_EXPLANATION" : "Wenn es einen Grund oder konkreten Auslöser für eine bestimmte Situation gab, wie hast Du darauf reagiert? Wie hast Du dich in dieser Situation verhalten? War es eine automatische Handlung/Reaktion oder konntest Du innehalten und dich bewusst für eine Reaktion entscheiden?",

	"QUESTION_FINISH_TITLE" : "Du bist fertig!",
	"QUESTION_FINISH_SUBTITLE" : "Bestätige, um deinen Eintrag auf dem Gerät zu speichern.",
	"QUESTION_FINISH_CONFIRM" : "Bestätige deinen Eintrag",

	"UI_DONE" : "Fertig",
	"UI_NO_SUGGESTIONS" : "Keine Vorschläge",

	"USER_TITLE" : "Ich",
	"SETTINGS_TITLE" : "EINSTELLUNGEN",
	"SETTINGS_DAILY_TARGET_TITLE" : "Tagesziel",
	"SETTINGS_DAILY_TARGET_JOURNAL" : "Eintrag",
	"SETTINGS_DAILY_TARGET_JOURNALS" : "Einträge",
	"SETTINGS_ABOUT" : "ÜBER",
	"SETTINGS_USER_GUIDE" : "Benutzerinformation",
	"SETTINGS_PRIVACY" : "Datenschutz",
	"SETTINGS_TERMS_CONDITIONS" : "Allg. Nutzungsbedingungen",
	"SETTINGS_VERSION" : "Version",
	"SETTINGS_ACCOUNT" : "KONTO",
	"SETTINGS_EDIT_PROFILE" : "Profil bearbeiten",
	"LOG_OUT" : "Abmelden"
}