module.exports = {
	"HOME_TITLE" : "Home",

	"HOME_MESSAGE_FIRST_OPEN" : "Wilkommen zu Arya! Durch Wischen kannst du deinen Lieblingshintergrund auswählen.",
	"HOME_MESSAGE_ZERO_JOURNALS" : "Mach dich an deinen ersten Eintrag für diese Woche",
	"HOME_MESSAGE_ONE_JOURNAL" : "eintrag diese Woche.",
	"HOME_MESSAGE_MULTIPLE_JOURNALS" : "einträge diese Woche.",

	"ME_TITLE" : "ICH",

	"JOURNALS_TITLE" : "Meine Einträge",
	"JOURNAL_TITLE" : "Mein Eintrag",
	"JOURNAL_UNANSWERED" : "Nicht beantwortet",

	"NOTES_TITLE" :"Meine Notizen",

	"QUESTION_FEELING_TITLE" : "Wie fühlst du dich? Jetzt und hier.",
	"QUESTION_FEELING_SUBTITLE" : "Stelle dein persönliches Stimmungsbarometer ein!",
	"QUESTION_FEELING_EXPLANATION" : "Spüre in dich hinein - Wie geht es dir gerade? Wie ist deine persönliche Verfassung? Heiter oder eher wolkig? Überlege dabei nicht allzu lange. Folge deinem Impuls und bewege den Regler, um deine momentane Stimmung einzustellen.",
	"QUESTION_FEELING_VERY_BAD" : "SEHR SCHLECHT",
	"QUESTION_FEELING_AVERAGE" : "DURCHSCHNITTLICH",
	"QUESTION_FEELING_VERY_WELL" : "SEHR GUT",

	"QUESTION_CIRCUMSTANCES_TITLE" : "Beschreibe die Situation und begründe sie.",
	"QUESTION_CIRCUMSTANCES_SUBTITLE" : "Wie ist deine persönliche Verfassung? Gibt es Ursachen/Auslöser für deine Stimmung?",
	"QUESTION_CIRCUMSTANCES_EXPLANATION" : "Denke kurz nach. Gibt es einen bestimmten Grund oder Auslöser für deine derzeitige Stimmung? Und wer oder was ist aus deiner Sicht dafür verantwortlich? Beschreibe die Situation samt Grund. Wenn dir dazu gerade nichts einfällt, dann beschreibe einfach nur diesen Moment. Orte, Tätigkeiten, beteiligte Menschen, Geräusche, Gerüche, Sonstiges - was auch immer dir dazu in den Sinn kommt.",

	"QUESTION_BODY_TITLE" : "Wie fühlt sich im Moment dein Körper an?",
	"QUESTION_BODY_SUBTITLE" : "Welche Empfindungen nimmst du wo in deinem Körper wahr?",
	"QUESTION_BODY_EXPLANATION" : "Nimm dir nochmal kurz Zeit und gehe auf innere Spurensuche. Was spürst du wo im Körper? Welche Empfindungen kannst du wahrnehmen? Wo ist dir warm und wohlig? Wo kribbelt’s? Wo ziept’s? Wo tut’s weh? Wo ist mehr Weite und wo ist alles enger als sonst? Hüpft das Herz oder krampft der Magen? Zuckt das Auge? Beobachte alles sorgfältig, tippe auf die Abbildung der Körperteile, um dort deine Empfindungen zu notieren.",

	"QUESTION_BODY_HEAD" : "Kopf",
	"QUESTION_BODY_NECK" : "Nacken",
	"QUESTION_BODY_CHEST" : "Brust",
	"QUESTION_BODY_ABDOMEN" : "Bauch",
	"QUESTION_BODY_UPPER_BACK" : "Oberer Rücken",
	"QUESTION_BODY_LOWER_BACK" : "Unterer Rücken",
	"QUESTION_BODY_HIP" : "Hüfte",
	"QUESTION_BODY_LEFT_SHOULDER" : "Linke Schulter",
	"QUESTION_BODY_LEFT_ELBOW" : "Linker Ellenbogen",
	"QUESTION_BODY_LEFT_HAND" : "Linke Hand",
	"QUESTION_BODY_LEFT_ARM" : "Linker Arm",
	"QUESTION_BODY_LEFT_THIGH" : "Linker Oberschenkel",
	"QUESTION_BODY_LEFT_KNEE" : "Linkes Knie",
	"QUESTION_BODY_LEFT_ANKLE" : "Linker Knöchel/Fuß",
	"QUESTION_BODY_LEFT_LEG" : "Linkes Bein",

	"QUESTION_BODY_RIGHT_SHOULDER" : "Rechte Schulter",
	"QUESTION_BODY_RIGHT_ELBOW" : "Rechter Ellenbogen",
	"QUESTION_BODY_RIGHT_HAND" : "Rechte Hand",
	"QUESTION_BODY_RIGHT_ARM" : "Rechter Arm",
	"QUESTION_BODY_RIGHT_THIGH" : "Rechter Oberschenkel",
	"QUESTION_BODY_RIGHT_KNEE" : "Rechtes Knie",
	"QUESTION_BODY_RIGHT_ANKLE" : "Rechter Knöchel/Fuß",
	"QUESTION_BODY_RIGHT_LEG" : "Rechtes Bein",

	"QUESTION_BODY_HEADACHE" : "Kopfschmerzen",
	"QUESTION_BODY_FLUSHED_FACE" : "Errötet",
	"QUESTION_BODY_DIZZY_AND_LIGHTHEADED" : "Schwindel und Bennommenheit",
	"QUESTION_BODY_HEAVYHEADED" : "Schwerer Kopf",
	"QUESTION_BODY_NECK_PAIN" : "Nackenschmerzen",

	"QUESTION_BODY_HEAD_OPTIONS" : ["Kopfschmerzen","Schwerer Kopf","Errötet","Brennende Augen","Ohrenschmerzen","Mundtrockenheit","Halsschmerz","Kloß im Hals","Sprachlosigkeit","Schwindel und Bennommenheit","Verwirrung","Klarheit","Zentriertheit","Fieber","Hitze","Wärme","Kälte","Leichtigkeit","Schwere","Jucken","Prickeln","Anspannung","Taubheit","Kribbeln"],
	"QUESTION_BODY_CHEST_OPTIONS" : ["Brustschmerzen","Druck auf der Brust","Herzrasen","Herzflattern","Liebe/Verbundenheit","Herzschmerz","Herzklopfen","Rückenschmerzen","Lockerheit","Steifheit","Nackenschmerzen","Schulterschmerzen","Steifheit","Hitze","Wärme","Kälte","Leichtigkeit","Schwere","Jucken","Prickeln","Anspannung","Taubheit","Kribbeln"],
	"QUESTION_BODY_ABDOMEN_OPTIONS" : ["Schmetterlinge im Bauch","Übelkeit","Magenschmerzen","Wohligkeit","Völlegefühl","Steifheit","Rückenschmerzen","Muskelschmerzen","Lockerheit","Hitze","Wärme","Kälte","Leichtigkeit","Schwere","Jucken","Prickeln","Anspannung","Taubheit","Kribbeln"],
	"QUESTION_BODY_LEFT_ARM_OPTIONS" : ["Gelenkschmerzen","Muskelschmerzen","Kalte Hände","Warme Hände","Feuchte Hände","Hitze","Wärme","Kälte","Leichtigkeit","Schwere","Jucken","Prickeln","Anspannung","Taubheit","Kribbeln"],
	"QUESTION_BODY_RIGHT_ARM_OPTIONS" : ["Gelenkschmerzen","Muskelschmerzen","Kalte Hände","Warme Hände","Feuchte Hände","Hitze","Wärme","Kälte","Leichtigkeit","Schwere","Jucken","Prickeln","Anspannung","Taubheit","Kribbeln"],
	"QUESTION_BODY_HIP_OPTIONS" : ["Unterleibsschmerzen","Wohligkeit","Blasen-/Nierenbeschwerden","Hitze","Kälte","Wärme","Leichtigkeit","Schwere","Jucken","Prickeln","Anspannung","Taubheit","Kribbeln"],
	"QUESTION_BODY_LEFT_LEG_OPTIONS" : ["Gelenkschmerzen","Muskelschmerzen","Kalte Füße","Warme Füße","Knieprobleme","Wärme","Hitze","Kälte","Leichtigkeit","Schwere","Jucken","Prickeln","Anspannung","Taubheit","Kribbeln"],
	"QUESTION_BODY_RIGHT_LEG_OPTIONS" : ["Gelenkschmerzen","Muskelschmerzen","Kalte Füße","Warme Füße","Knieprobleme","Wärme","Hitze","Kälte","Leichtigkeit","Schwere","Jucken","Prickeln","Anspannung","Taubheit","Kribbeln"],
	"QUESTION_BODY_GENERIC_OPTIONS" : [],

	"QUESTION_BODY_CHEST_PAIN" : "Brustschmerzen",
	"QUESTION_BODY_BREATHING" : "Atemprobleme",
	"QUESTION_BODY_PRESSURE_CHEST" : "Druck auf der Brust",
	"QUESTION_BODY_HEARTBEAT" : "Herzrasen",
	"QUESTION_BODY_BACK_PAIN" : "Rückenschmerzen",
	"QUESTION_BODY_STIFNESS" : "Steifheit",

	"QUESTION_BODY_DIGESTIVE" : "Magenschmerzen",
	"QUESTION_BODY_NAUSEOUS" : "Übelkeit",
	"QUESTION_BODY_CROTCH" : "Unterleibsschmerzen",

	"QUESTION_BODY_MUSCLE_ACHE" : "Muskelschmerzen",
	"QUESTION_BODY_JOINT_PAIN" : "Gelenkschmerzen",
	"QUESTION_BODY_NUMBNESS" : "Taubheit",
	"QUESTION_BODY_TINGLING" : "Kribbeln",

	"QUESTION_THOUGHTS_TITLE" : "Was denkst du gerade?",
	"QUESTION_THOUGHTS_SUBTITLE" : "Welche Gedanken kommen hoch? Notiere ohne zu Bewerten.",
	"QUESTION_THOUGHTS_EXPLANATION" : "Vielleicht schließt du kurz die Augen, nimmst für ein paar Sekunden deinen Atem wahr. Dann bist du in der besten Position um deine Gedanken zu beobachten. Wie Wolken am Himmel kommen sie und ziehen auch wieder davon, mal stürmisch, mal gemach. Lass sie ziehen, aber bitte schreib sie auf. Fälle dabei kein Urteil.",

	"QUESTION_REACTION_TITLE" : "Wie hast du darauf reagiert?",
	"QUESTION_REACTION_SUBTITLE" : "Halte deine Reaktionen fest. Vielleicht fällt dir dabei etwas auf. Etwas, das dir nicht bewusst war oder etwas ganz Neues oder eine Veränderung in deinem Verhalten.",
	"QUESTION_REACTION_EXPLANATION" : "Wenn es einen Grund oder konkreten Auslöser für eine bestimmte Situation gab, wie hast du darauf reagiert? Wie hast du dich in dieser Situation verhalten? War es eine automatische Handlung/Reaktion oder konntest du innehalten und dich bewusst für eine Reaktion entscheiden? (Wie) hat sich deine Reaktion verändert?",

	"QUESTION_FINISH_TITLE" : "Zusammenfassung deines heutigen Tagebuch-Eintrags.",
	"QUESTION_FINISH_SUBTITLE" : "Folgend kannst du all deine Eingaben noch einmal anschauen. Um deinen Tagebuch-Eintrag zu archivieren, ist es erforderlich dass du ihn dir selbst per E-Mail schickst. Sonst war er ‘nur’ eine gute Übung!",
	"QUESTION_FINISH_CONFIRM" : "Bestätige deinen Eintrag",

	"UI_DONE" : "Fertig",
	"UI_NO_SUGGESTIONS" : "Keine Vorschläge",

	"USER_TITLE" : "Ich",
	"SETTINGS_TITLE" : "EINSTELLUNGEN",
	"SETTINGS_DAILY_TARGET_TITLE" : "Tagesziel",
	"SETTINGS_DAILY_TARGET_JOURNAL" : "Eintrag",
	"SETTINGS_DAILY_TARGET_JOURNALS" : "Einträge",
	"SETTINGS_ABOUT" : "ÜBER",
	"SETTINGS_USER_GUIDE" : "Benutzerinformation",
	"SETTINGS_PRIVACY" : "Datenschutz",
	"SETTINGS_TERMS_CONDITIONS" : "Allg. Nutzungsbedingungen",
	"SETTINGS_VERSION" : "Version",
	"SETTINGS_ACCOUNT" : "KONTO",
	"SETTINGS_EDIT_PROFILE" : "Profil bearbeiten",
	"LOG_OUT" : "Abmelden",

  "INTRO_MESSAGES" : [
		'Hallo! Schön, dass du wieder da bist. Hast du die Sonne im Herzen oder ist sie nur irgendwo im Aussen? Bring dein Innerstes auf den Punkt. Es lohnt sich...',
		'Stille Nacht, lange Nacht? Das ist ganz wunderbar. Denn in der Stille ist es einfacher uns selbst zu hören. Welche Töne nimmst du in dir wahr? Geht es dir gut?',
		'Hallo! Thich Nhat Hanh hat gesagt: "Wenn die Achtsamkeit etwas Schönes berührt, offenbart sie dessen Schönheit. Wenn sie etwas Schmerzvolles berührt, wandelt sie es um und heilt es." Wir wünschen dir viel Schönes und Heilsames!',
		'“Das einzig Unveränderliche ist die Veränderung” (Tao Te King). Dem Winter folgt der Sommer, wie auch jedes Gefühl vergeht und jedem Gedanken folgt ein neuer, aber jeder Moment ist einzigartig. Horche in dein persönliches Hier und Jetzt hinein. Viel Spaß :)',
		'“Es liegt in der Macht der Menschen, zwischen Glück und Weh zu wählen” (Pearl S. Buck) - wähle das Glück und sei ganz im Hier und Jetzt. Bleibe achtsam und verliere es nicht aus den Augen!',
		'Hallo! “Die hilfreichste Hand hängt an deinem eigenen Arm” (belgisches Sprichwort). Du allein hast dein Leben in der Hand, entscheide dich heute wieder für ein erfülltes und achtsames Leben.',
		'“Wenn man die Dinge versteht, sind sie, wie sie sind. Wenn man sie nicht versteht, sind sie, wie sie sind” Wir müssen nicht immer alles verstehen, es reicht einfach nur da zu sein.',
		'Hallo! Ist dir, bei deiner Einkehr in Körper, Geist und Seele, schon etwas an dir aufgefallen? Wie geht es dir jetzt damit? Viel Freude heute!',
		'Nur wenn du für dich da sein kannst, kannst du auch für andere da sein. Es ist so heilsam, dass du dir diese Zeit für dich nimmst! Alles Liebe und Gute für dich!',
		'Glück entsteht oft durch Aufmerksamkeit in kleinen Dingen, Unglück oft durch Vernachlässigung kleiner Dinge. (Wilhelm Busch). Lenke jetzt wieder deine Aufmerksamkeit auf die kleinen Dinge und Freuden in dir und begegne dem Glück. Wir freuen uns mit dir.',
		'“Alles, was wir für uns selbst tun, tun wir auch für andere, und alles, was wir für andere tun, tun wir auch für uns selbst” (Thich Nath Hanh) Tue dir selbst und der Welt etwas Gutes und sei bewusst und achtsam in Gedanken, Worten und Taten.',
		'Hallo! “Die wahre Lebenskunst besteht darin, im Alltäglichen das Wunderbare zu sehen.” (Pearl S. Buck) - Achte heute auf das Wunderbare.',
		'Hallo! “Alles, was ich heute tue, ist wichtig, gebe ich doch einen ganzen Tag meines Lebens dafür” (George Bernard Shaw) Sei gut zu dir und verbringe einen wunder-vollen Tag!',
		'Du bist dort, wo deine Gedanken sind. Sieh zu, dass deine Gedanken da sind, wo du sein möchtest.(Rabbi Nachman von Bratzlaw) - Nun gut… Bringe deine Gedanken auf den Punkt. Gute Einsicht!',
		'Achte gut auf diesen Tag, denn genau er ist das Leben - Sei liebevoll und voller Achtsamkeit. Alles Gute!',
	],
	"OUTRO_MESSAGES" : [
		'Danke dir!  Komm bald wieder… zurück zu dir ;-)',
		'Danke. Wir freuen uns mit dir! Denn wieder bist du dir ein Stück selbst begegnet.',
		'Schön, dass du schon wieder da warst!',
		'Danke. Das war’s für heute, zumindest auf ‘dem Papier’...',
		'Danke. Pass weiterhin gut auf dich auf.',
		'Es ist so gut, dass du hier warst. Danke dir für dich!',
		'Danke dir! Versuche mal weiterhin achtsam zu bleiben… und Wunder geschehen...',
		'Dankeschön. Wir wünschen dir einen Tag voller Liebe und Achtsamkeit!',
		'Achtsame und herzliche Grüße für dich! Vergiss nicht… allem geht der Geist voran.',
		'Danke dir! Du warst schon fleißig und hast auf dich geachtet - wir finden heute ist eine Belohnung fällig :)',
		'Danke dir selbst dafür, dass du auf dich achtest. Und gebe dir in Gedanken eine liebevolle Umarmung.',
		'Danke! Bleib bei dir! Es lohnt sich… hast du morgen schon was vor ;-)?',
		'Gut gemacht :) Wie oft warst du schon hier? Jede Reise fängt mit den ersten Schritten an….',
		'Das ist jetzt kein Werbetext. Ganz aufrichtig: Wir freuen uns, dass du dabei bist - Danke!',
		'Danke dir! Wenn du noch eine Minute Zeit hast, sitze still und spüre wie sich das anfühlt. Wir hoffen es kommt Freude und Dankbarkeit für diesen Tag auf!',
	]

}